"""empty message

Revision ID: ba98752e66b6
Revises: 
Create Date: 2023-12-07 08:44:13.294489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba98752e66b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('pro_number', sa.String(length=50), nullable=True),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('shipper_id', sa.Integer(), nullable=True),
    sa.Column('consignee_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('magic_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['consignee_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['shipper_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_laser_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('link_date', sa.DateTime(), nullable=True),
    sa.Column('is_linked', sa.Boolean(), nullable=True),
    sa.Column('laser_order_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_receipt_id', sa.Integer(), nullable=True),
    sa.Column('laser_attachment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_receipt_id'], ['warehouse_receipt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_receipt_id')
    )
    op.create_table('receipt_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('piece_description', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('hazardous', sa.Boolean(), nullable=True),
    sa.Column('bonded_type', sa.String(length=50), nullable=True),
    sa.Column('warehouse_receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_receipt_id'], ['warehouse_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_line')
    op.drop_table('receipt_laser_link')
    op.drop_table('warehouse_receipt')
    op.drop_table('purchase_order')
    op.drop_table('note')
    op.drop_table('invoice')
    op.drop_table('contact')
    # ### end Alembic commands ###
