"""po number string size

Revision ID: 19e9cf6b4847
Revises: 0594fed5f51b
Create Date: 2023-11-22 11:37:25.401651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19e9cf6b4847'
down_revision = '0594fed5f51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.alter_column('po_number',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.alter_column('po_number',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
