"""Magic Id.

Revision ID: e0263bd26656
Revises: 2b32d7f458c3
Create Date: 2023-08-28 12:01:45.599437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0263bd26656'
down_revision = '2b32d7f458c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magic_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_receipt', schema=None) as batch_op:
        batch_op.drop_column('magic_id')

    # ### end Alembic commands ###
